<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MapGenerator.CombatSim</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MapGenerator.Combat\MapGenerator.Combat.csproj" />
    <ProjectReference Include="..\MapGenerator.Application\MapGenerator.Application.csproj" />
  </ItemGroup>
</Project>
